# Generated by Django 5.1.4 on 2024-12-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
    ]
