# Generated by Django 5.1.4 on 2024-12-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_management', '0001_initial'),
        ('patient_management', '0001_initial'),
        ('rooms_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='rooms_management.room'),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_appointments', to='doctor_management.doctorprofile'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='doctor_management.doctorprofile'),
        ),
    ]
