# Generated by Django 5.1.4 on 2024-12-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurse_management', '0001_initial'),
        ('patient_management', '0002_initial'),
        ('rooms_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nursepatientupdate',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_patient_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursepatientupdate',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_updates', to='patient_management.patientprofile'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurseroomassignment',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_room_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurseroomassignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_room_updates', to='patient_management.patientprofile'),
        ),
        migrations.AddField(
            model_name='nurseroomassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assigned_rooms', to='rooms_management.room'),
        ),
    ]
