# Generated by Django 5.1.4 on 2024-12-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursepatientupdate',
            name='update_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurseroomassignment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
