# Generated by Django 5.1.4 on 2024-12-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_management', '0002_initial'),
        ('patient_management', '0003_initial'),
        ('records_management', '0001_initial'),
        ('rooms_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_records', to='doctor_management.doctorprofile'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patient_management.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_records', to='rooms_management.room'),
        ),
    ]
