# Generated by Django 5.1.4 on 2024-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
